export const chatTools = [
  { name: 'get_hebrew_app_status', description: 'Get Hebrew app database status, including written lessons and audio readiness.', inputSchema: { type: 'object', properties: { limit: { type: 'number' } } } },
  { name: 'draft_hebrew_lesson_bundle', description: 'Create or update an unpublished Hebrew lesson draft.', inputSchema: { type: 'object', required: ['title'], properties: { title: { type: 'string' }, slug: { type: 'string' }, book: { type: 'string' }, chapter: { type: 'number' }, verse_start: { type: 'number' }, verse_end: { type: 'number' }, lesson_json: {}, flashcards_json: {}, verses: { type: 'array' } } } },
  { name: 'preview_hebrew_lesson_bundle', description: 'Preview a Hebrew lesson bundle.', inputSchema: { type: 'object', properties: { lesson_id: { type: 'string' }, lessonId: { type: 'string' }, slug: { type: 'string' } } } },
  { name: 'publish_hebrew_lesson_bundle', description: 'Add an approved Hebrew lesson bundle to the study tables.', inputSchema: { type: 'object', properties: { lesson_id: { type: 'string' }, lessonId: { type: 'string' }, slug: { type: 'string' } } } },
  { name: 'list_pending_hebrew_lessons', description: 'List unpublished Hebrew lesson drafts.', inputSchema: { type: 'object', properties: { limit: { type: 'number' } } } },
  { name: 'prepare_hebrew_audio_track', description: 'Create or update a hidden Hebrew audio track and its complete ordered segment script. The verse must already exist in the Hebrew verse table.', inputSchema: { type: 'object', required: ['verse_reference', 'audio_segments'], properties: { verse_reference: { type: 'string' }, lesson_id: { type: 'string' }, track_title: { type: 'string' }, script_version: { type: 'string' }, audio_segments: { type: 'array', items: { type: 'object' } } } } },
  { name: 'generate_next_hebrew_audio_segment', description: 'Generate exactly one missing, changed, or failed segment for a prepared Hebrew audio track. Repeat until ready is true.', inputSchema: { type: 'object', properties: { verse_reference: { type: 'string' }, track_id: { type: 'string' } } } },
  { name: 'get_hebrew_audio_status', description: 'Inspect strict Hebrew audio readiness, metadata completeness, errors, duration, and optional live stream checks.', inputSchema: { type: 'object', properties: { verse_reference: { type: 'string' }, track_id: { type: 'string' }, verify_streams: { type: 'boolean' } } } },
];
